import {
  Appointment,
  DashboardStats,
  Location,
  Service,
  ServiceCategory,
  Staff,
  Tenant,
} from '../types';
import { DEFAULT_WORKING_HOURS } from './constants';

export const INITIAL_TENANT: Tenant = {
  id: 't-venus-01',
  name: 'کلینیک تخصصی زیبایی و لیزر ونوس',
  phone: '02122409876',
  address: 'تهران، زعفرانیه، خیابان مقدس اردبیلی، مجتمع پالادیوم، برج شمالی، طبقه ۶',
  logo: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=150&auto=format&fit=crop&q=80',
  instagram: 'venus_beauty_clinic',
  description: 'ارائه تخصصی‌ترین خدمات لیزر الکس کندلا ۲۰۲۴، جوانسازی و فیشیال پوست تحت نظر پزشکان متخصص',
  working_hours: DEFAULT_WORKING_HOURS,
};

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: 'loc-1',
    name: 'شعبه مرکزی (زعفرانیه)',
    address: 'تهران، زعفرانیه، خیابان مقدس اردبیلی، مجتمع پالادیوم، طبقه ۶، واحد ۶۰۲',
    city: 'تهران',
    phone: '02122409876',
    is_active: true,
  },
  {
    id: 'loc-2',
    name: 'شعبه سعادت‌آباد',
    address: 'تهران، سعادت‌آباد، میدان کاج، خیابان سرو غربی، پلاک ۳۴، طبقه ۲',
    city: 'تهران',
    phone: '02122081234',
    is_active: true,
  },
];

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  { id: 'cat-1', name: 'لیزر موهای زائد', description: 'دستگاه الکساندرایت کندلا جنتل پرو ۲۰۲۴', display_order: 1 },
  { id: 'cat-2', name: 'مراقبت و فیشیال پوست', description: 'پاکسازی عمیق، هیدروفیشیال و جوانسازی', display_order: 2 },
  { id: 'cat-3', name: 'تزریقات زیبایی و پزشکی', description: 'بوتاکس مصپورت و دیسپورت، فیلر و مزوتراپی', display_order: 3 },
  { id: 'cat-4', name: 'خدمات تخصصی ناخن', description: 'کاشت پودر، ژلیش، لمینت و مانیکور روسی', display_order: 4 },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-1',
    tenant_id: 't-venus-01',
    category_id: 'cat-1',
    name: 'لیزر فول بادی بانوان (کندلا ۲۰۲۴)',
    description: 'شامل دست‌ها، پاها، زیربغل، بیکینی، خط باسن، شکم و گودی کمر با سری اختصاصی',
    duration_minutes: 60,
    price: 1250000,
    is_active: true,
  },
  {
    id: 'srv-2',
    tenant_id: 't-venus-01',
    category_id: 'cat-1',
    name: 'لیزر کاربردی بانوان (ساق، ساعد، بیکینی، زیربغل)',
    description: 'پکیج اقتصادی و پرطرفدار نواحی اصلی بدون درد با سیستم کولینگ کرایو',
    duration_minutes: 40,
    price: 850000,
    is_active: true,
  },
  {
    id: 'srv-3',
    tenant_id: 't-venus-01',
    category_id: 'cat-2',
    name: 'فیشیال تخصصی VIP و پاکسازی عمیق',
    description: 'مراحل ۱۰ گانه تخلیه کومودون، اسیدتراپی ملایم، اکسیژن‌رسانی، ماسک طلا و نوردرمانی',
    duration_minutes: 75,
    price: 1650000,
    is_active: true,
  },
  {
    id: 'srv-4',
    tenant_id: 't-venus-01',
    category_id: 'cat-3',
    name: 'تزریق بوتاکس مصپورت (کل پیشانی و خط اخم)',
    description: 'رفع چین و چروک پیشانی، خط اخم و پنجه کلاغی دور چشم با داروی اصل دارای برچسب اصالت',
    duration_minutes: 30,
    price: 980000,
    is_active: true,
  },
  {
    id: 'srv-5',
    tenant_id: 't-venus-01',
    category_id: 'cat-3',
    name: 'تزریق فیلر لب روسی (هر سی‌سی آلیاکسین)',
    description: 'فرم‌دهی طبیعی لب با فیلر هیالورونیک اسید برند معتبر همراه با بی‌حسی کامل',
    duration_minutes: 45,
    price: 2900000,
    is_active: true,
  },
  {
    id: 'srv-6',
    tenant_id: 't-venus-01',
    category_id: 'cat-4',
    name: 'کاشت ژل و لمینت ناخن با مانیکور روسی',
    description: 'استحکام‌سازی ناخن طبیعی با متریال ضدقارچ و دیزاین اختصاصی به انتخاب مشتری',
    duration_minutes: 90,
    price: 680000,
    is_active: true,
  },
  {
    id: 'srv-7',
    tenant_id: 't-venus-01',
    category_id: 'cat-2',
    name: 'مزونیدلینگ و مزوتراپی جوانسازی فیوژن',
    description: 'کوکتل‌های تخصصی سفت‌کننده و روشن‌کننده لک‌های پوستی با کارتریج نانو',
    duration_minutes: 50,
    price: 1450000,
    is_active: true,
  },
];

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'stf-1',
    name: 'دکتر سارا رضوانی',
    role: 'پزشک پوست و زیبایی',
    bio: 'بیش از ۱۲ سال سابقه در زمینه تزریقات زیبایی، لیفت با نخ و جوانسازی پیشرفته صورت',
    avatar: 'https://images.unsplash.com/photo-1594824813583-059ba2785d0d?w=150&auto=format&fit=crop&q=80',
    phone: '09121112233',
    is_active: true,
    specialties: ['بوتاکس', 'فیلر لب', 'مزوتراپی'],
  },
  {
    id: 'stf-2',
    name: 'مهسا افشار',
    role: 'اپراتور ارشد لیزر',
    bio: 'دارای سرتیفیکیت کار با تجهیزات لیزر کندلا و سایناشور با بیش از ۵ سال تجربه مداوم',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '09123334455',
    is_active: true,
    specialties: ['لیزر فول بادی', 'لیزر کاربردی'],
  },
  {
    id: 'stf-3',
    name: 'نیلوفر صدر',
    role: 'مستر فیشیالیست و اسکین‌تراپیست',
    bio: 'مدرک بین‌المللی تالگو فرانسه، متخصص درمان لک، آکنه و احیای سد دفاعی پوست',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '09125556677',
    is_active: true,
    specialties: ['فیشیال VIP', 'اسیدتراپی', 'مزونیدلینگ'],
  },
  {
    id: 'stf-4',
    name: 'الهام کریمی',
    role: 'متخصص خدمات ناخن',
    bio: 'دارای مدرک گرند مستر روسیه در تکنیک‌های مانیکور کمبی و ژل‌پولیش بدون آسیب',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    phone: '09127778899',
    is_active: true,
    specialties: ['کاشت ژل', 'لمینت ناخن'],
  },
];

// Helper to generate dynamic dates around today
function getDateOffset(hoursOffset: number): string {
  const d = new Date();
  d.setHours(d.getHours() + hoursOffset);
  return d.toISOString();
}

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    customer_name: 'مریم شریفی',
    customer_phone: '09129876543',
    service_id: 'srv-1',
    staff_id: 'stf-2',
    location_id: 'loc-1',
    starts_at: getDateOffset(1),
    ends_at: getDateOffset(2),
    status: 'pending',
    price: 1250000,
    reference_code: 'UNT-8401',
    notes: 'جلسه چهارم لیزر، پوست سبزه، تنظیم شات با درجه متوسط',
    service_name: 'لیزر فول بادی بانوان (کندلا ۲۰۲۴)',
    staff_name: 'مهسا افشار',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 60,
  },
  {
    id: 'apt-2',
    customer_name: 'پروانه کاظمی',
    customer_phone: '09123456789',
    service_id: 'srv-3',
    staff_id: 'stf-3',
    location_id: 'loc-1',
    starts_at: getDateOffset(2.5),
    ends_at: getDateOffset(3.75),
    status: 'confirmed',
    price: 1650000,
    reference_code: 'UNT-8402',
    notes: 'پوست دهیدراته و دارای لک ملایم، درخواست ماسک جلبک ویژه',
    service_name: 'فیشیال تخصصی VIP و پاکسازی عمیق',
    staff_name: 'نیلوفر صدر',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 75,
  },
  {
    id: 'apt-3',
    customer_name: 'الهه صادقی',
    customer_phone: '09351239874',
    service_id: 'srv-4',
    staff_id: 'stf-1',
    location_id: 'loc-1',
    starts_at: getDateOffset(4),
    ends_at: getDateOffset(4.5),
    status: 'confirmed',
    price: 980000,
    reference_code: 'UNT-8403',
    notes: 'تمدید بوتاکس بعد از ۵ ماه، درخواست بررسی خط لبخند',
    service_name: 'تزریق بوتاکس مصپورت (کل پیشانی و خط اخم)',
    staff_name: 'دکتر سارا رضوانی',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 30,
  },
  {
    id: 'apt-4',
    customer_name: 'زهرا معتمد',
    customer_phone: '09124445566',
    service_id: 'srv-5',
    staff_id: 'stf-1',
    location_id: 'loc-2',
    starts_at: getDateOffset(5.5),
    ends_at: getDateOffset(6.25),
    status: 'pending',
    price: 2900000,
    reference_code: 'UNT-8404',
    notes: 'بار اول، مشاوره قبل از تزریق فرم طبیعی',
    service_name: 'تزریق فیلر لب روسی (هر سی‌سی آلیاکسین)',
    staff_name: 'دکتر سارا رضوانی',
    location_name: 'شعبه سعادت‌آباد',
    duration_minutes: 45,
  },
  {
    id: 'apt-5',
    customer_name: 'پریسا همتی',
    customer_phone: '09198889900',
    service_id: 'srv-6',
    staff_id: 'stf-4',
    location_id: 'loc-1',
    starts_at: getDateOffset(-2),
    ends_at: getDateOffset(-0.5),
    status: 'completed',
    price: 680000,
    reference_code: 'UNT-8399',
    notes: 'طراحی فرنچ مات با لمینت هلویی، پرداخت نقدی انجام شد',
    service_name: 'کاشت ژل و لمینت ناخن با مانیکور روسی',
    staff_name: 'الهام کریمی',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 90,
  },
  {
    id: 'apt-6',
    customer_name: 'نگین رفیعی',
    customer_phone: '09367776655',
    service_id: 'srv-2',
    staff_id: 'stf-2',
    location_id: 'loc-1',
    starts_at: getDateOffset(-4),
    ends_at: getDateOffset(-3.3),
    status: 'completed',
    price: 850000,
    reference_code: 'UNT-8395',
    notes: 'جلسه سوم کاربردی بدون عوارض قبلی',
    service_name: 'لیزر کاربردی بانوان (ساق، ساعد، بیکینی، زیربغل)',
    staff_name: 'مهسا افشار',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 40,
  },
  {
    id: 'apt-7',
    customer_name: 'سمیرا نادری',
    customer_phone: '09121119988',
    service_id: 'srv-7',
    staff_id: 'stf-3',
    location_id: 'loc-2',
    starts_at: getDateOffset(24), // Tomorrow
    ends_at: getDateOffset(24.8),
    status: 'confirmed',
    price: 1450000,
    reference_code: 'UNT-8410',
    notes: 'جلسه دوم مزونیدلینگ، کرم ترمیم‌کننده همراه داشته باشد',
    service_name: 'مزونیدلینگ و مزوتراپی جوانسازی فیوژن',
    staff_name: 'نیلوفر صدر',
    location_name: 'شعبه سعادت‌آباد',
    duration_minutes: 50,
  },
  {
    id: 'apt-8',
    customer_name: 'کیانا درخشان',
    customer_phone: '09123332211',
    service_id: 'srv-1',
    staff_id: 'stf-2',
    location_id: 'loc-1',
    starts_at: getDateOffset(-26), // Yesterday
    ends_at: getDateOffset(-25),
    status: 'no_show',
    price: 1250000,
    reference_code: 'UNT-8380',
    notes: 'تماس بی‌پاسخ بود و مراجعه نفرمودند',
    service_name: 'لیزر فول بادی بانوان (کندلا ۲۰۲۴)',
    staff_name: 'مهسا افشار',
    location_name: 'شعبه مرکزی (زعفرانیه)',
    duration_minutes: 60,
  },
];

export const INITIAL_DASHBOARD_STATS: DashboardStats = {
  today_appointments: 6,
  today_revenue: 8330000,
  pending_bookings: 2,
  completed_bookings: 2,
  total_customers: 248,
  weekly_stats: [
    { day: 'sat', day_name: 'شنبه', count: 12, revenue: 14200000 },
    { day: 'sun', day_name: 'یکشنبه', count: 9, revenue: 10800000 },
    { day: 'mon', day_name: 'دوشنبه', count: 15, revenue: 18500000 },
    { day: 'tue', day_name: 'سه‌شنبه', count: 11, revenue: 12900000 },
    { day: 'wed', day_name: 'چهارشنبه', count: 14, revenue: 16700000 },
    { day: 'thu', day_name: 'پنج‌شنبه', count: 18, revenue: 22400000 },
    { day: 'fri', day_name: 'جمعه', count: 4, revenue: 4800000 },
  ],
};
